# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  TMDB_API_KEY: $(TMDB_API_KEY)

stages:
- stage: Build
  displayName: Build images
  jobs:
  - job: Build
    displayName: Build with Docker Compose
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      displayName: Build all services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        action: BuildServices
        projectName: 'seenit'
        additionalImageTags: |
          $(Build.BuildId)


